# swagger\u914D\u7F6E
springdoc:
  version: '1.0.0'
  packagesToScan: com.ace.reslutswagger.controller # \u5305\u626B\u63CF\u8DEF\u5F84
  swagger-ui:
    path: /swagger-ui.html # swagger-ui\u8BBF\u95EE\u8DEF\u5F84 http://ip:\u7AEF\u53E3/swagger-ui.html
    csrf:
      enabled: true # \u542F\u7528CSRF\u652F\u6301
    enabled: true # \u5F00\u542Fswagger-ui
    display-request-duration: true # \u5C55\u793A\u8BF7\u6C42\u6240\u8017\u65F6\u95F4ms
    operations-sorter: method # API\u6392\u5E8F\u65B9\u5F0F\uFF1Aalpha-\u5B57\u6BCD\uFF0Cmethod-http\u65B9\u6CD5
    groups-order: desc # \u6392\u5E8F\u987A\u5E8F
    disable-swagger-default-url: true # \u7981\u7528swagger-ui\uFF1B\u9ED8\u8BA4\u7684petstore\u7F51\u5740\uFF0C\u9ED8\u8BA4\u5C31\u662Fswagger-ui.html
  model-and-view-allowed: true # \u8FD0\u884CmodelAndView\u5C55\u793A\uFF08\u8FD4\u56DE\u9875\u9762\uFF09
  show-actuator: true # \u52A0\u4E86spring-boot-actuator\u4F9D\u8D56\u7684\u53EF\u5F00\u542F
  group-configs:
    - group: account
      paths-to-match: /accountTbl/**
    - group: functions
      packages-to-scan: com.ace.reslutswagger.controller
